/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    media: Media;
    users: User;
    team: Team;
    projects: Project;
    products: Product;
    services: Service;
    faq: Faq;
    insights: Insight;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Write a post, keep it with Save Draft, or make it live with Publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The post's title.
   */
  title: string;
  /**
   * Write the post body. Use the toolbar above for formatting.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * One or two sentences shown on list pages (optional).
   */
  excerpt?: string | null;
  /**
   * Optional. If left blank, the Korean title is shown instead.
   */
  titleEn?: string | null;
  /**
   * Optional. If left blank, the Korean content is shown instead.
   */
  contentEn?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional. If left blank, the Korean excerpt is shown instead.
   */
  excerptEn?: string | null;
  /**
   * Large image shown at the top of the post (optional).
   */
  banner?: (number | null) | Media;
  /**
   * Auto-generated from the title. Edit only if you know why.
   */
  slug: string;
  /**
   * Filled in automatically the first time you publish.
   */
  publishedAt?: string | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Image library for posts — banner images are uploaded here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * A short phrase describing the image (screen readers, search).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * The roster shown on the Company → Team panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  /**
   * The Latin-script name (e.g. Matt) — this is the primary displayed name.
   */
  name: string;
  /**
   * Optional — some members have no Korean name on file.
   */
  nameKo?: string | null;
  role: string;
  /**
   * Optional. If left blank, the Korean role is shown instead.
   */
  roleEn?: string | null;
  group: 'mgmt' | 'dev' | 'design' | 'qa' | 'biz' | 'tbc';
  /**
   * e.g. /site/team/Matt.webp — leave blank if there is no photo.
   */
  photo?: string | null;
  /**
   * Home's six-face teaser shows the first 6 in this order.
   */
  order: number;
  /**
   * Auto-generated from the name. Edit only if you know why.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Projects shown on the Work list and project detail pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Short category tag shown above the title.
   */
  tag?: string | null;
  title: string;
  desc?: string | null;
  tagEn?: string | null;
  /**
   * Optional. If left blank, the Korean title is shown instead.
   */
  titleEn?: string | null;
  descEn?: string | null;
  /**
   * The detail page's summary list. Enter Korean and English side by side on each row.
   */
  bullets?:
    | {
        item: string;
        itemEn?: string | null;
        id?: string | null;
      }[]
    | null;
  cat: 'health' | 'edu' | 'lang' | 'prod';
  /**
   * ProjectArt.tsx's presentation key — a hand-mapped constant, edit only if you know why.
   */
  art: 'cells' | 'plate' | 'grid' | 'bubbles' | 'translate' | 'card' | 'checklist' | 'wave' | 'layers';
  order: number;
  /**
   * The project detail page's URL.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Products shown on the Work list and product detail pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * e.g. SkinArch — v3 never translates a product's own name.
   */
  name: string;
  cat?: string | null;
  lead: string;
  whoH?: string | null;
  who?: string | null;
  /**
   * The Research-Use-Only disclaimer. Leave blank where it doesn't apply (e.g. wiz).
   */
  note?: string | null;
  catEn?: string | null;
  leadEn?: string | null;
  whoHEn?: string | null;
  whoEn?: string | null;
  noteEn?: string | null;
  feats?:
    | {
        title: string;
        titleEn?: string | null;
        body?: string | null;
        bodyEn?: string | null;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        title: string;
        titleEn?: string | null;
        body?: string | null;
        bodyEn?: string | null;
        id?: string | null;
      }[]
    | null;
  facts?:
    | {
        label: string;
        labelEn?: string | null;
        body?: string | null;
        bodyEn?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The detail page's "Related" rail. A project's label is plain text; a service's label needs both languages.
   */
  rel?:
    | {
        kind: 'project' | 'service';
        refId?: string | null;
        abbr: string;
        label?: string | null;
        labelEn?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The Work product card's short technical tags. v3 never translates these.
   */
  teaserChips?:
    | {
        chip: string;
        id?: string | null;
      }[]
    | null;
  ruo?: boolean | null;
  priceKey: 'priceAsk' | 'monthly';
  /**
   * Internal reference key for the product page.
   */
  topic: string;
  order: number;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Services the Work panel and the product/project "Related" rails reference.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * The svc-detail view's main body paragraph.
   */
  body?: string | null;
  /**
   * The short teaser shown on the Work panel's band.
   */
  blurb?: string | null;
  nameEn?: string | null;
  bodyEn?: string | null;
  blurbEn?: string | null;
  /**
   * The svc-detail view's "Related" rail. Only a static entry carries its own label (both languages).
   */
  related?:
    | {
        kind: 'project' | 'product' | 'static';
        refId?: string | null;
        abbr: string;
        label?: string | null;
        labelEn?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The English-only technical-term chips shown under the svc-detail body.
   */
  chips?:
    | {
        chip: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The dictionary key the "Related" rail's caption uses.
   */
  relatedCaption: 'relatedLabel' | 'relatedProducts';
  number: string;
  code: string;
  abbr: string;
  /**
   * The #svc-* id the Work services panel anchors to.
   */
  anchor: string;
  /**
   * SpectrogramStack band weight — only "insight" deviates from 1.
   */
  weight?: number | null;
  order: number;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Question/answer pairs shown in Home's FAQ module.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * Optional. If left blank, the Korean question is shown instead.
   */
  questionEn?: string | null;
  /**
   * Optional. If left blank, the Korean answer is shown instead.
   */
  answerEn?: string | null;
  /**
   * Home shows only the first 4 in this order.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Company news, product notes and case notes shown on the Company → Insights panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  heading: string;
  body?: string | null;
  /**
   * Optional. If left blank, the Korean heading is shown instead.
   */
  headingEn?: string | null;
  /**
   * Optional. If left blank, the Korean body is shown instead.
   */
  bodyEn?: string | null;
  kind: 'news' | 'product' | 'case';
  /**
   * e.g. "2026 · 03" or "2023" — a display string, not a parseable date.
   */
  date: string;
  /**
   * Optional. Either an external link, or an internal path such as /work/products.
   */
  link?: {
    href?: string | null;
    external?: boolean | null;
    /**
     * The dictionary label key for an internal link (optional).
     */
    labelKey?: 'segProducts' | null;
  };
  order: number;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  excerpt?: T;
  titleEn?: T;
  contentEn?: T;
  excerptEn?: T;
  banner?: T;
  slug?: T;
  publishedAt?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  nameKo?: T;
  role?: T;
  roleEn?: T;
  group?: T;
  photo?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  tag?: T;
  title?: T;
  desc?: T;
  tagEn?: T;
  titleEn?: T;
  descEn?: T;
  bullets?:
    | T
    | {
        item?: T;
        itemEn?: T;
        id?: T;
      };
  cat?: T;
  art?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  cat?: T;
  lead?: T;
  whoH?: T;
  who?: T;
  note?: T;
  catEn?: T;
  leadEn?: T;
  whoHEn?: T;
  whoEn?: T;
  noteEn?: T;
  feats?:
    | T
    | {
        title?: T;
        titleEn?: T;
        body?: T;
        bodyEn?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        titleEn?: T;
        body?: T;
        bodyEn?: T;
        id?: T;
      };
  facts?:
    | T
    | {
        label?: T;
        labelEn?: T;
        body?: T;
        bodyEn?: T;
        id?: T;
      };
  rel?:
    | T
    | {
        kind?: T;
        refId?: T;
        abbr?: T;
        label?: T;
        labelEn?: T;
        id?: T;
      };
  teaserChips?:
    | T
    | {
        chip?: T;
        id?: T;
      };
  ruo?: T;
  priceKey?: T;
  topic?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  body?: T;
  blurb?: T;
  nameEn?: T;
  bodyEn?: T;
  blurbEn?: T;
  related?:
    | T
    | {
        kind?: T;
        refId?: T;
        abbr?: T;
        label?: T;
        labelEn?: T;
        id?: T;
      };
  chips?:
    | T
    | {
        chip?: T;
        id?: T;
      };
  relatedCaption?: T;
  number?: T;
  code?: T;
  abbr?: T;
  anchor?: T;
  weight?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  questionEn?: T;
  answerEn?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  headingEn?: T;
  bodyEn?: T;
  kind?: T;
  date?: T;
  link?:
    | T
    | {
        href?: T;
        external?: T;
        labelKey?: T;
      };
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}